# Generated by Django 3.2.12 on 2022-03-19 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0002_auto_20220319_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='shelter',
            name='id',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(max_length=50, primary_key=models.BigAutoField(primary_key=True), serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=200, primary_key=models.BigAutoField(primary_key=True), serialize=False),
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, primary_key=models.BigAutoField(primary_key=True), serialize=False),
        ),
    ]
