# Generated by Django 3.2.12 on 2022-03-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0004_auto_20220319_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
