# Generated by Django 3.2.12 on 2022-03-19 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0005_alter_shelter_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.RemoveField(
            model_name='dog',
            name='shelter',
        ),
        migrations.AddField(
            model_name='dog',
            name='shelter_name',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='dog_shelters.shelter', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelter',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
