# Generated by Django 3.2.12 on 2022-03-19 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0009_auto_20220319_1722'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='shelter_id',
        ),
        migrations.AddField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.PROTECT, primary_key=django.db.models.fields.AutoField, serialize=False, to='dog_shelters.shelter'),
            preserve_default=False,
        ),
    ]
