# Generated by Django 3.2.12 on 2022-03-19 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0010_auto_20220319_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='id',
            field=models.AutoField(auto_created=True, default=-1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dog_shelters.shelter'),
        ),
    ]
