# Generated by Django 3.2.12 on 2022-03-19 17:25

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dog_shelters', '0011_auto_20220319_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='id',
        ),
        migrations.AlterField(
            model_name='dog',
            name='shelter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=django.db.models.fields.BigAutoField, serialize=False, to='dog_shelters.shelter'),
        ),
    ]
